name: Bug Report
description: Report a bug or issue with the Fat Zebra Next.js library
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us resolve the issue quickly.

  - type: input
    id: version
    attributes:
      label: Library Version
      description: What version of @fwc/fat-zebra-nextjs are you using?
      placeholder: "0.5.6"
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Which environment are you using?
      options:
        - Sandbox
        - Live/Production
    validations:
      required: true

  - type: input
    id: nextjs-version
    attributes:
      label: Next.js Version
      description: What version of Next.js are you using?
      placeholder: "14.2.30"
    validations:
      required: true

  - type: input
    id: react-version
    attributes:
      label: React Version
      description: What version of React are you using?
      placeholder: "18.3.1"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: If applicable, add a minimal code sample that reproduces the issue
      render: typescript
      placeholder: |
        ```typescript
        // Your code sample here
        ```

  - type: textarea
    id: error
    attributes:
      label: Error Message/Stack Trace
      description: If applicable, paste the complete error message and stack trace
      render: shell

  - type: textarea
    id: environment-details
    attributes:
      label: Environment Details
      description: Add any other context about your environment
      placeholder: |
        - OS: [e.g. macOS 14.1]
        - Browser: [e.g. Chrome 120.0]
        - Node.js: [e.g. 20.10.0]
        - TypeScript: [e.g. 5.7.2]

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have tested this with the latest version of the library
          required: true
        - label: I have provided a minimal code sample that reproduces the issue
          required: false
        - label: This issue is not related to Fat Zebra's API directly (use their support for API issues)
          required: true