name: Feature Request
description: Suggest a new feature or enhancement for the Fat Zebra Next.js library
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide detailed information about your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem? Please describe the problem you're trying to solve.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered
      placeholder: I have also considered...

  - type: dropdown
    id: component
    attributes:
      label: Component Area
      description: Which part of the library would this feature affect?
      options:
        - PaymentForm component
        - React hooks (usePayment, useOAuthPayment, etc.)
        - Server-side functions
        - TypeScript types/interfaces
        - Utilities and helpers
        - Documentation
        - Build/packaging
        - Other
    validations:
      required: true

  - type: textarea
    id: api-design
    attributes:
      label: Proposed API Design
      description: If applicable, show how you envision the API for this feature
      render: typescript
      placeholder: |
        ```typescript
        // Example API design
        const { newFeature } = usePayment({
          enableNewFeature: true
        });
        ```

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my project
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case and how this feature would help
      placeholder: In my application, I need to...
    validations:
      required: true

  - type: checkboxes
    id: compatibility
    attributes:
      label: Compatibility Considerations
      description: Please consider the following
      options:
        - label: This feature should maintain backward compatibility
          required: false
        - label: I understand this might require a major version update
          required: false
        - label: This feature aligns with Fat Zebra's API capabilities
          required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request