parameters:
- name: nodeVersion
  type: string
  default: '20'
- name: runCoverage
  type: boolean
  default: false

steps:
- task: NodeTool@0
  inputs:
    versionSpec: ${{ parameters.nodeVersion }}
  displayName: 'Setup Node.js ${{ parameters.nodeVersion }}'

- task: Cache@2
  inputs:
    key: 'npm | "$(Agent.OS)" | package-lock.json'
    restoreKeys: |
      npm | "$(Agent.OS)"
    path: ~/.npm
  displayName: 'Cache npm'

- script: npm ci
  displayName: 'Install dependencies'

- script: npm run test
  displayName: 'Run tests'

- ${{ if eq(parameters.runCoverage, true) }}:
  - script: npm run testcoverage
    displayName: 'Run tests with coverage'
    
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: 'coverage/cobertura-coverage.xml'
      reportDirectory: 'coverage'
    displayName: 'Publish coverage results'
    condition: always()
    
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'coverage/junit