# Azure DevOps security pipeline
- task: CredScan@3
  inputs:
    toolMajorVersion: 'V2'
    
- task: ComponentGovernanceComponentDetection@0
  inputs:
    scanType: 'Register'
    verbosity: 'Verbose'
    alertWarningLevel: 'High'